"""
neo MCP server — expose neo's read surface to Claude Code as tools.

Hand-rolled JSON-RPC 2.0 over stdio, stdlib only. Spec: MCP 2025-06-18.

Self-reference handling: every tool has an ``include_self`` parameter
(default false). When false, queries against ``hook_events`` filter out
rows tagged ``source='neo_mcp_call'`` — those are events generated by
this server's own tool calls (PreToolUse / PostToolUse fires when Claude
calls one of these tools). Flip ``include_self`` to true to audit the
observer overhead explicitly.

Other tables (telemetry, sessions, agents, messages, system_reminders,
memory_files) aren't bloated by query activity — they come from disk
artifacts and regex extraction, not from MCP traffic — so they're not
tagged.
"""

from __future__ import annotations

import fcntl
import json
import os
import sys
import threading
import time
import traceback
from pathlib import Path
from typing import Any, Callable

from . import db
from . import states
from . import tokens
from .app import get_setup_status, serve as _serve_dashboard, sync_installed_probe

PROTOCOL_VERSION = "2025-06-18"
SERVER_NAME = "neo"
SERVER_VERSION = "0.1.0"
DASHBOARD_PORT = 7777
# Periodic re-ingest interval for the dashboard-owner process.
INGEST_INTERVAL_SEC = 30
# Filesystem lock that ensures only one neo-mcp process per host runs the
# heavy ingest + dashboard. Released automatically by the kernel when the
# owning process exits, so a follower picks up the role on the next startup.
OWNER_LOCK_PATH = Path.home() / ".neo" / ".mcp-owner.lock"

# Env-var escape hatches: set to "0" to opt out of the background work.
ENV_PERIODIC = "NEO_MCP_PERIODIC_INGEST"
ENV_DASHBOARD = "NEO_MCP_DASHBOARD"

SELF_FILTER_SQL = "(source IS NULL OR source != 'neo_mcp_call')"

_dashboard_started = False
_dashboard_lock = threading.Lock()
_owner_lock_handle = None  # kept open for the lifetime of the owning process


def _env_enabled(name: str, default: bool = True) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() not in {"0", "false", "no", "off", ""}


def _try_acquire_owner_role() -> bool:
    """Claim the per-host dashboard+ingest role via a non-blocking fcntl lock.

    Returns True if we got it (we are the owner), False if another neo-mcp
    process on this host already owns it (we are a follower).
    """
    global _owner_lock_handle
    try:
        OWNER_LOCK_PATH.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
        handle = open(OWNER_LOCK_PATH, "w")
    except OSError:
        return False
    try:
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
    except (BlockingIOError, OSError):
        handle.close()
        return False
    _owner_lock_handle = handle
    return True


def _periodic_ingest() -> None:
    while True:
        time.sleep(INGEST_INTERVAL_SEC)
        try:
            db.ingest_all()
        except Exception:
            traceback.print_exc(file=sys.stderr)


def _start_dashboard() -> None:
    global _dashboard_started
    with _dashboard_lock:
        if _dashboard_started:
            return
        _dashboard_started = True

    if not _try_acquire_owner_role():
        # Another neo-mcp on this host already owns ingest + dashboard.
        # As a follower we still serve MCP tool calls against the shared
        # SQLite DB, but we do no ingest and bind no ports — so spawning
        # extra Claude sessions no longer multiplies CPU.
        return

    try:
        sync_installed_probe()
    except Exception:
        traceback.print_exc(file=sys.stderr)

    periodic_enabled = _env_enabled(ENV_PERIODIC, default=True)
    dashboard_enabled = _env_enabled(ENV_DASHBOARD, default=True)

    if periodic_enabled:
        # Initial ingest is incremental — cheap when nothing changed. Run it
        # in its own thread so initialize() isn't blocked on the cold path.
        threading.Thread(
            target=_initial_ingest,
            daemon=True,
            name="neo-initial-ingest",
        ).start()
        threading.Thread(
            target=_periodic_ingest,
            daemon=True,
            name="neo-periodic-ingest",
        ).start()

    if dashboard_enabled:
        threading.Thread(
            target=_serve_dashboard,
            args=(DASHBOARD_PORT, False),
            daemon=True,
            name="neo-dashboard",
        ).start()


def _initial_ingest() -> None:
    try:
        db.ingest_all()
    except Exception:
        traceback.print_exc(file=sys.stderr)


# ── helpers ─────────────────────────────────────────────────────────


def _hook_filter(include_self: bool) -> str:
    return "" if include_self else f" AND {SELF_FILTER_SQL}"


def _hook_where(include_self: bool) -> str:
    return "" if include_self else f" WHERE {SELF_FILTER_SQL}"


def _bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "on"}
    if isinstance(value, (int, float)):
        return bool(value)
    return default


def _int(value: Any, default: int, minimum: int = 0, maximum: int | None = None) -> int:
    try:
        v = int(value) if value is not None else default
    except (TypeError, ValueError):
        v = default
    if v < minimum:
        v = minimum
    if maximum is not None and v > maximum:
        v = maximum
    return v


def _text_result(payload: Any) -> dict:
    if not isinstance(payload, str):
        payload = json.dumps(payload, default=str, indent=2)
    return {"content": [{"type": "text", "text": payload}]}


# ── tool implementations ────────────────────────────────────────────


def tool_status(_args: dict) -> Any:
    return get_setup_status()


def tool_summary(args: dict) -> Any:
    include_self = _bool(args.get("include_self"))
    base = db.summary()
    if not include_self:
        rows = db.query(
            f"SELECT COUNT(*) AS c, MAX(timestamp) AS t FROM hook_events{_hook_where(False)}"
        )
        if rows:
            base["hook_events"] = rows[0]["c"]
            base["latest_hook_timestamp"] = rows[0]["t"]
    base["self_filter"] = "excluded" if not include_self else "included"
    return base


def tool_data_accounting(_args: dict) -> Any:
    return tokens.summary()


def tool_query_reminders(args: dict) -> Any:
    limit = _int(args.get("limit"), 50, minimum=1, maximum=500)
    return db.query(
        "SELECT source_file, line_number, content, timestamp "
        "FROM system_reminders "
        "ORDER BY COALESCE(timestamp, '') DESC, source_file DESC, line_number DESC "
        "LIMIT ?",
        (limit,),
    )


def tool_query_sessions(args: dict) -> Any:
    limit = _int(args.get("limit"), 100, minimum=1, maximum=500)
    project = args.get("project")
    if project:
        return db.query(
            "SELECT project, session_id, mtime, agent_count, compaction_count "
            "FROM sessions WHERE project = ? ORDER BY mtime DESC LIMIT ?",
            (project, limit),
        )
    return db.query(
        "SELECT project, session_id, mtime, agent_count, compaction_count "
        "FROM sessions ORDER BY mtime DESC LIMIT ?",
        (limit,),
    )


def tool_query_agents(args: dict) -> Any:
    limit = _int(args.get("limit"), 50, minimum=1, maximum=500)
    project = args.get("project")
    session_id = args.get("session_id")
    expand_id = args.get("agent_id")
    if expand_id:
        agent_id = _int(expand_id, 0, minimum=1, maximum=10_000_000)
        meta = db.query(
            "SELECT id, project, session_id, file_name, is_compaction, mtime, "
            "size_bytes, message_count FROM agents WHERE id = ?",
            (agent_id,),
        )
        msgs = db.query(
            "SELECT idx, role, content FROM messages WHERE agent_id = ? ORDER BY idx LIMIT 1000",
            (agent_id,),
        )
        return {"agent": meta[0] if meta else None, "messages": msgs}

    clauses = []
    params: list[Any] = []
    if project:
        clauses.append("project = ?")
        params.append(project)
    if session_id:
        clauses.append("session_id = ?")
        params.append(session_id)
    where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
    params.append(limit)
    return db.query(
        f"SELECT id, project, session_id, file_name, is_compaction, mtime, size_bytes, message_count "
        f"FROM agents{where} ORDER BY mtime DESC LIMIT ?",
        tuple(params),
    )


def tool_query_probe_events(args: dict) -> Any:
    limit = _int(args.get("limit"), 100, minimum=1, maximum=500)
    include_self = _bool(args.get("include_self"))
    event_type = args.get("event_type")

    clauses = []
    params: list[Any] = []
    if not include_self:
        clauses.append(SELF_FILTER_SQL)
    if event_type:
        clauses.append("event_type = ?")
        params.append(event_type)
    where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
    params.append(limit)
    rows = db.query(
        f"SELECT timestamp, event_type, source, data_json FROM hook_events{where} "
        f"ORDER BY timestamp DESC LIMIT ?",
        tuple(params),
    )
    for row in rows:
        if isinstance(row.get("data_json"), str):
            try:
                row["data"] = json.loads(row["data_json"])
            except json.JSONDecodeError:
                row["data"] = row["data_json"]
            row.pop("data_json", None)
    return rows


def tool_query_telemetry(args: dict) -> Any:
    limit = _int(args.get("limit"), 100, minimum=1, maximum=500)
    return db.query(
        "SELECT time, event, session_id, parent_session_id, device_id, version, "
        "model, platform, arch FROM telemetry ORDER BY time DESC LIMIT ?",
        (limit,),
    )


def tool_query_memory_files(args: dict) -> Any:
    limit = _int(args.get("limit"), 100, minimum=1, maximum=500)
    project = args.get("project")
    if project:
        return db.query(
            "SELECT project, file_name, content FROM memory_files "
            "WHERE project = ? ORDER BY file_name LIMIT ?",
            (project, limit),
        )
    return db.query(
        "SELECT project, file_name, content FROM memory_files "
        "ORDER BY project, file_name LIMIT ?",
        (limit,),
    )


def tool_state_model(args: dict) -> Any:
    include_self = _bool(args.get("include_self"))
    limit = _int(args.get("limit"), 1000, minimum=1, maximum=5000)
    diagram = states.get_state_diagram()
    rows = db.query(
        f"SELECT timestamp, event_type, data_json AS data FROM hook_events"
        f"{_hook_where(include_self)} ORDER BY timestamp DESC LIMIT ?",
        (limit,),
    )
    rows.reverse()
    for row in rows:
        if isinstance(row.get("data"), str):
            try:
                row["data"] = json.loads(row["data"])
            except json.JSONDecodeError:
                pass
    return {"diagram": diagram, "analysis": states.analyze_session(rows)}


def tool_correlations(args: dict) -> Any:
    include_self = _bool(args.get("include_self"))
    timeline_limit = _int(args.get("timeline_limit"), 720, minimum=1, maximum=5000)
    project_limit = _int(args.get("project_limit"), 50, minimum=1, maximum=500)
    event_limit = _int(args.get("event_limit"), 50, minimum=1, maximum=500)

    hook_timeline = db.query(
        "SELECT minute, count, event_type FROM ("
        f"SELECT substr(timestamp, 1, 16) AS minute, COUNT(*) AS count, event_type "
        f"FROM hook_events{_hook_where(include_self)} GROUP BY minute, event_type "
        f"ORDER BY minute DESC LIMIT ?"
        ") ORDER BY minute",
        (timeline_limit,),
    )
    hook_totals = db.query(
        f"SELECT event_type, COUNT(*) AS count FROM hook_events{_hook_where(include_self)} "
        f"GROUP BY event_type ORDER BY count DESC LIMIT ?",
        (event_limit,),
    )
    agents_per_project = db.query(
        "SELECT project, COUNT(*) AS total, "
        "SUM(CASE WHEN is_compaction=1 THEN 1 ELSE 0 END) AS compactions, "
        "SUM(CASE WHEN is_compaction=0 THEN 1 ELSE 0 END) AS agents, "
        "SUM(message_count) AS total_messages "
        "FROM agents GROUP BY project ORDER BY total DESC LIMIT ?",
        (project_limit,),
    )
    return {
        "hook_timeline": hook_timeline,
        "hook_totals": hook_totals,
        "agents_per_project": agents_per_project,
    }


def tool_tokens_report(_args: dict) -> Any:
    s = tokens.summary()
    return s["totals"]


# ── tool registry ───────────────────────────────────────────────────


TOOLS: dict[str, dict] = {
    "status": {
        "description": (
            "Setup health: whether ~/.claude/settings.json exists, neo's probe is "
            "installed, and how many hook commands are wired."
        ),
        "schema": {"type": "object", "properties": {}, "additionalProperties": False},
        "fn": tool_status,
    },
    "summary": {
        "description": (
            "Top-level counts across all tables: telemetry rows, sessions, agents, "
            "messages, memory files, hook events, system reminders. Defaults exclude "
            "self-traffic from neo's MCP server (set include_self=true to include)."
        ),
        "schema": {
            "type": "object",
            "properties": {
                "include_self": {
                    "type": "boolean",
                    "default": False,
                    "description": "Include hook events generated by this MCP server's own tool calls.",
                },
            },
            "additionalProperties": False,
        },
        "fn": tool_summary,
    },
    "data_accounting": {
        "description": (
            "Visible vs hidden data ratios estimated from local transcript file "
            "sizes and channel structure. Includes per-session breakdown, hidden %, "
            "data multiplier, and estimated transmission count. NOT real token "
            "counts — for those, run /usage in Claude Code."
        ),
        "schema": {"type": "object", "properties": {}, "additionalProperties": False},
        "fn": tool_data_accounting,
    },
    "query_reminders": {
        "description": (
            "System reminder rows extracted from raw transcript JSONL — the hidden "
            "instructions injected into user messages. Includes source file path, "
            "line number, content, and timestamp."
        ),
        "schema": {
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 500},
            },
            "additionalProperties": False,
        },
        "fn": tool_query_reminders,
    },
    "query_sessions": {
        "description": "Session list across all projects with agent / compaction counts.",
        "schema": {
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "default": 100, "minimum": 1, "maximum": 500},
                "project": {"type": "string", "description": "Filter to one project name."},
            },
            "additionalProperties": False,
        },
        "fn": tool_query_sessions,
    },
    "query_agents": {
        "description": (
            "Agent / subagent / compaction transcripts. Pass agent_id to expand one "
            "agent's full message list (up to 1000 messages); otherwise returns metadata only."
        ),
        "schema": {
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 500},
                "project": {"type": "string"},
                "session_id": {"type": "string"},
                "agent_id": {"type": "integer", "description": "If set, returns the agent + its messages."},
            },
            "additionalProperties": False,
        },
        "fn": tool_query_agents,
    },
    "query_probe_events": {
        "description": (
            "Recent hook events captured by the probe — PreToolUse, PostToolUse, "
            "Notification, etc. Excludes neo's own MCP call traffic by default."
        ),
        "schema": {
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "default": 100, "minimum": 1, "maximum": 500},
                "event_type": {"type": "string", "description": "Filter by event_type (e.g. 'pretool')."},
                "include_self": {
                    "type": "boolean",
                    "default": False,
                    "description": "Include neo's own MCP-call hook events.",
                },
            },
            "additionalProperties": False,
        },
        "fn": tool_query_probe_events,
    },
    "query_telemetry": {
        "description": (
            "Telemetry rows that were retained on disk — includes device fingerprint, "
            "session id, parent session id, model, platform, arch."
        ),
        "schema": {
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "default": 100, "minimum": 1, "maximum": 500},
            },
            "additionalProperties": False,
        },
        "fn": tool_query_telemetry,
    },
    "query_memory_files": {
        "description": "Persistent memory files seeded by Claude Code instances per project.",
        "schema": {
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "default": 100, "minimum": 1, "maximum": 500},
                "project": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "fn": tool_query_memory_files,
    },
    "state_model": {
        "description": (
            "Heuristic state model: returns the state diagram (states + transitions + "
            "anomaly definitions) plus an analysis of recent hook events with "
            "inferred state timeline, hidden vs visible state counts, and detected "
            "anomalies (rapid reminders, telemetry bursts, compaction cascades, etc.)."
        ),
        "schema": {
            "type": "object",
            "properties": {
                "limit": {"type": "integer", "default": 1000, "minimum": 1, "maximum": 5000},
                "include_self": {"type": "boolean", "default": False},
            },
            "additionalProperties": False,
        },
        "fn": tool_state_model,
    },
    "correlations": {
        "description": (
            "Cross-signal patterns: hook event timeline by minute, hook totals by "
            "type, agent counts per project."
        ),
        "schema": {
            "type": "object",
            "properties": {
                "timeline_limit": {"type": "integer", "default": 720, "minimum": 1, "maximum": 5000},
                "project_limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 500},
                "event_limit": {"type": "integer", "default": 50, "minimum": 1, "maximum": 500},
                "include_self": {"type": "boolean", "default": False},
            },
            "additionalProperties": False,
        },
        "fn": tool_correlations,
    },
    "tokens_report": {
        "description": (
            "Compact totals from data_accounting — sessions analyzed, visible/hidden "
            "MB, multiplier, hidden %, transmissions, system reminders, sidechain / "
            "subagent / compaction counts."
        ),
        "schema": {"type": "object", "properties": {}, "additionalProperties": False},
        "fn": tool_tokens_report,
    },
}


# ── JSON-RPC dispatch ───────────────────────────────────────────────


class RpcError(Exception):
    def __init__(self, code: int, message: str, data: Any = None):
        super().__init__(message)
        self.code = code
        self.message = message
        self.data = data


def _err(code: int, message: str, data: Any = None) -> dict:
    err = {"code": code, "message": message}
    if data is not None:
        err["data"] = data
    return err


def _handle_initialize(_params: dict) -> dict:
    threading.Thread(target=_start_dashboard, daemon=True, name="neo-dashboard-init").start()
    return {
        "protocolVersion": PROTOCOL_VERSION,
        "capabilities": {"tools": {"listChanged": False}},
        "serverInfo": {"name": SERVER_NAME, "version": SERVER_VERSION},
    }


def _handle_tools_list(_params: dict) -> dict:
    return {
        "tools": [
            {
                "name": name,
                "description": spec["description"],
                "inputSchema": spec["schema"],
            }
            for name, spec in TOOLS.items()
        ]
    }


def _handle_tools_call(params: dict) -> dict:
    name = params.get("name")
    if not name or name not in TOOLS:
        raise RpcError(-32602, f"unknown tool: {name}")
    args = params.get("arguments") or {}
    if not isinstance(args, dict):
        raise RpcError(-32602, "arguments must be an object")
    try:
        result = TOOLS[name]["fn"](args)
        return _text_result(result)
    except Exception as exc:
        traceback.print_exc(file=sys.stderr)
        return {
            "content": [{"type": "text", "text": f"tool error: {exc}"}],
            "isError": True,
        }


METHODS: dict[str, Callable[[dict], dict]] = {
    "initialize": _handle_initialize,
    "tools/list": _handle_tools_list,
    "tools/call": _handle_tools_call,
}


def _dispatch(msg: dict) -> dict | None:
    method = msg.get("method")
    msg_id = msg.get("id")
    params = msg.get("params") or {}

    if method is None:
        return {"jsonrpc": "2.0", "id": msg_id, "error": _err(-32600, "missing method")}

    if method.startswith("notifications/") or msg_id is None:
        return None

    handler = METHODS.get(method)
    if handler is None:
        return {"jsonrpc": "2.0", "id": msg_id, "error": _err(-32601, f"method not found: {method}")}

    try:
        result = handler(params)
        return {"jsonrpc": "2.0", "id": msg_id, "result": result}
    except RpcError as exc:
        return {"jsonrpc": "2.0", "id": msg_id, "error": _err(exc.code, exc.message, exc.data)}
    except Exception as exc:
        traceback.print_exc(file=sys.stderr)
        return {"jsonrpc": "2.0", "id": msg_id, "error": _err(-32603, f"internal error: {exc}")}


def _send(response: dict) -> None:
    sys.stdout.write(json.dumps(response, default=str) + "\n")
    sys.stdout.flush()


def serve() -> None:
    for raw in sys.stdin:
        line = raw.strip()
        if not line:
            continue
        try:
            msg = json.loads(line)
        except json.JSONDecodeError:
            _send({"jsonrpc": "2.0", "id": None, "error": _err(-32700, "parse error")})
            continue
        if not isinstance(msg, dict):
            continue
        response = _dispatch(msg)
        if response is not None:
            _send(response)


def main() -> None:
    serve()


if __name__ == "__main__":
    main()
